# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build Play App for development"
  lane :playBuild do
    gradle(task: "assemblePlayDebug")
  end

  desc "Build Play App for release"
  lane :playRelease do
    gradle(task: "assemblePlayRelease")
  end

  desc "Build Foss App for development"
  lane :fossBuild do
    gradle(task: "assembleFossDebug")
  end

  desc "Build Foss App for release"
  lane :fossRelease do
    gradle(task: "assembleFossRelease")
  end

  desc "Upload App to Play store"
  lane :beta do
    upload_to_play_store(
      track: 'beta', 
      apk: 'app/build/outputs/apk/release/app-release.apk'
    )
  end
end
